---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[flexget::default]
    attributes:
      flexget:
        plugin_dependencies:
          transmissionrpc:
